#random seed can be empty
randomSeed: 42

fuzzer:
    maxDepth: 15
    plusStarGaussianSigma: 2.0
    questionBernoulliProp: .8

selector:
    minHeight: 0
    maxHeight: 10
    allowedTypes:
        literal: Yes
        primitiveType: Yes
        numericType: Yes
        integralType: Yes
        floatingPointType: Yes
        referenceType: Yes
        classOrInterfaceType: Yes
        classType: Yes
        classType_lf_classOrInterfaceType: Yes
        classType_lfno_classOrInterfaceType: Yes
        interfaceType: Yes
        interfaceType_lf_classOrInterfaceType: Yes
        interfaceType_lfno_classOrInterfaceType: Yes
        typeVariable: Yes
        arrayType: Yes
        dims: Yes
        typeParameter: Yes
        typeParameterModifier: Yes
        typeBound: Yes
        additionalBound: Yes
        typeArguments: Yes
        typeArgumentList: Yes
        typeArgument: Yes
        wildcard: Yes
        wildcardBounds: Yes
        packageName: Yes
        typeName: Yes
        packageOrTypeName: Yes
        expressionName: Yes
        methodName: Yes
        ambiguousName: Yes
        compilationUnit: Yes
        packageDeclaration: Yes
        packageModifier: Yes
        importDeclaration: Yes
        singleTypeImportDeclaration: Yes
        typeImportOnDemandDeclaration: Yes
        singleStaticImportDeclaration: Yes
        staticImportOnDemandDeclaration: Yes
        typeDeclaration: Yes
        classDeclaration: Yes
        normalClassDeclaration: Yes
        classModifier: Yes
        typeParameters: Yes
        typeParameterList: Yes
        superclass: Yes
        superinterfaces: Yes
        interfaceTypeList: Yes
        classBody: Yes
        classBodyDeclaration: Yes
        classMemberDeclaration: Yes
        fieldDeclaration: Yes
        fieldModifier: Yes
        variableDeclaratorList: Yes
        variableDeclarator: Yes
        variableDeclaratorId: Yes
        variableInitializer: Yes
        unannType: Yes
        unannPrimitiveType: Yes
        unannReferenceType: Yes
        unannClassOrInterfaceType: Yes
        unannClassType: Yes
        unannClassType_lf_unannClassOrInterfaceType: Yes
        unannClassType_lfno_unannClassOrInterfaceType: Yes
        unannInterfaceType: Yes
        unannInterfaceType_lf_unannClassOrInterfaceType: Yes
        unannInterfaceType_lfno_unannClassOrInterfaceType: Yes
        unannTypeVariable: Yes
        unannArrayType: Yes
        methodDeclaration: Yes
        methodModifier: Yes
        methodHeader: Yes
        result: Yes
        methodDeclarator: Yes
        formalParameterList: Yes
        formalParameters: Yes
        formalParameter: Yes
        variableModifier: Yes
        lastFormalParameter: Yes
        receiverParameter: Yes
        throws_: Yes
        exceptionTypeList: Yes
        exceptionType: Yes
        methodBody: Yes
        instanceInitializer: Yes
        staticInitializer: Yes
        constructorDeclaration: Yes
        constructorModifier: Yes
        constructorDeclarator: Yes
        simpleTypeName: Yes
        constructorBody: Yes
        explicitConstructorInvocation: Yes
        enumDeclaration: Yes
        enumBody: Yes
        enumConstantList: Yes
        enumConstant: Yes
        enumConstantModifier: Yes
        enumBodyDeclarations: Yes
        interfaceDeclaration: Yes
        normalInterfaceDeclaration: Yes
        interfaceModifier: Yes
        extendsInterfaces: Yes
        interfaceBody: Yes
        interfaceMemberDeclaration: Yes
        constantDeclaration: Yes
        constantModifier: Yes
        interfaceMethodDeclaration: Yes
        interfaceMethodModifier: Yes
        annotationTypeDeclaration: Yes
        annotationTypeBody: Yes
        annotationTypeMemberDeclaration: Yes
        annotationTypeElementDeclaration: Yes
        annotationTypeElementModifier: Yes
        defaultValue: Yes
        annotation: Yes
        normalAnnotation: Yes
        elementValuePairList: Yes
        elementValuePair: Yes
        elementValue: Yes
        elementValueArrayInitializer: Yes
        elementValueList: Yes
        markerAnnotation: Yes
        singleElementAnnotation: Yes
        arrayInitializer: Yes
        variableInitializerList: Yes
        block: Yes
        blockStatements: Yes
        blockStatement: Yes
        localVariableDeclarationStatement: Yes
        localVariableDeclaration: Yes
        statement: Yes
        statementNoShortIf: Yes
        statementWithoutTrailingSubstatement: Yes
        emptyStatement_: Yes
        labeledStatement: Yes
        labeledStatementNoShortIf: Yes
        expressionStatement: Yes
        statementExpression: Yes
        ifThenStatement: Yes
        ifThenElseStatement: Yes
        ifThenElseStatementNoShortIf: Yes
        assertStatement: Yes
        switchStatement: Yes
        switchBlock: Yes
        switchBlockStatementGroup: Yes
        switchLabels: Yes
        switchLabel: Yes
        enumConstantName: Yes
        whileStatement: Yes
        whileStatementNoShortIf: Yes
        doStatement: Yes
        forStatement: Yes
        forStatementNoShortIf: Yes
        basicForStatement: Yes
        basicForStatementNoShortIf: Yes
        forInit: Yes
        forUpdate: Yes
        statementExpressionList: Yes
        enhancedForStatement: Yes
        enhancedForStatementNoShortIf: Yes
        breakStatement: Yes
        continueStatement: Yes
        returnStatement: Yes
        throwStatement: Yes
        synchronizedStatement: Yes
        tryStatement: Yes
        catches: Yes
        catchClause: Yes
        catchFormalParameter: Yes
        catchType: Yes
        finally_: Yes
        tryWithResourcesStatement: Yes
        resourceSpecification: Yes
        resourceList: Yes
        resource: Yes
        primary: Yes
        primaryNoNewArray: Yes
        primaryNoNewArray_lf_arrayAccess: Yes
        primaryNoNewArray_lfno_arrayAccess: Yes
        primaryNoNewArray_lf_primary: Yes
        primaryNoNewArray_lf_primary_lf_arrayAccess_lf_primary: Yes
        primaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary: Yes
        primaryNoNewArray_lfno_primary: Yes
        primaryNoNewArray_lfno_primary_lf_arrayAccess_lfno_primary: Yes
        primaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary: Yes
        classInstanceCreationExpression: Yes
        classInstanceCreationExpression_lf_primary: Yes
        classInstanceCreationExpression_lfno_primary: Yes
        typeArgumentsOrDiamond: Yes
        fieldAccess: Yes
        fieldAccess_lf_primary: Yes
        fieldAccess_lfno_primary: Yes
        arrayAccess: Yes
        arrayAccess_lf_primary: Yes
        arrayAccess_lfno_primary: Yes
        methodInvocation: Yes
        methodInvocation_lf_primary: Yes
        methodInvocation_lfno_primary: Yes
        argumentList: Yes
        methodReference: Yes
        methodReference_lf_primary: Yes
        methodReference_lfno_primary: Yes
        arrayCreationExpression: Yes
        dimExprs: Yes
        dimExpr: Yes
        constantExpression: Yes
        expression: Yes
        lambdaExpression: Yes
        lambdaParameters: Yes
        inferredFormalParameterList: Yes
        lambdaBody: Yes
        assignmentExpression: Yes
        assignment: Yes
        leftHandSide: Yes
        assignmentOperator: Yes
        conditionalExpression: Yes
        conditionalOrExpression: Yes
        conditionalAndExpression: Yes
        inclusiveOrExpression: Yes
        exclusiveOrExpression: Yes
        andExpression: Yes
        equalityExpression: Yes
        relationalExpression: Yes
        shiftExpression: Yes
        additiveExpression: Yes
        multiplicativeExpression: Yes
        unaryExpression: Yes
        preIncrementExpression: Yes
        preDecrementExpression: Yes
        unaryExpressionNotPlusMinus: Yes
        postfixExpression: Yes
        postIncrementExpression: Yes
        postIncrementExpression_lf_postfixExpression: Yes
        postDecrementExpression: Yes
        postDecrementExpression_lf_postfixExpression: Yes
        castExpression: Yes
